apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-scheduler-extender
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-scheduler-extender
subjects:
  - kind: ServiceAccount
    name: edge-scheduler-extender
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-scheduler-extender
  namespace: kube-system
data:
  edge-scheduler-extender.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: edge-scheduler-extender
    leaderElection:
      leaderElect: false
    extenders:
    - urlPrefix: "http://localhost:8000"
      enableHTTPS: false
      filterVerb: "filter"
      prioritizeVerb: "prioritize"
      bindVerb: "bind"
      weight: 1
      nodeCacheCapable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: edge-scheduler-extender
    tier: control-plane
  name: edge-scheduler-extender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: edge-scheduler-extender
      tier: control-plane
  template:
    metadata:
      labels:
        component: edge-scheduler-extender
        tier: control-plane
    spec:
      serviceAccountName: edge-scheduler-extender
      containers:
        - name: kube-scheduler
          image: registry.k8s.io/kube-scheduler:v1.29.0
          command:
            - kube-scheduler
            - --config=/etc/kubernetes/edge-scheduler-extender.yaml
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
          resources:
            requests:
              cpu: '0.1'
          volumeMounts:
            - name: config-volume
              mountPath: /etc/kubernetes
        - name: edge-scheduler-extender
          image: your-registry/edge-scheduler:latest
          env:
            - name: USE_SERVICE_ACCOUNT
              value: "true"
            - name: KUBE_NAMESPACE
              value: "kube-system"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
          ports:
            - containerPort: 8000
            - containerPort: 9001
              protocol: UDP
            - containerPort: 9002
              protocol: UDP
      volumes:
        - name: config-volume
          configMap:
            name: edge-scheduler-extender 