apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/app/.kube/config"
leaderElection:
  leaderElect: false
profiles:
  - schedulerName: edge-scheduler
    plugins:
      filter:
        enabled:
          - name: NodeResourcesFit
          - name: NodeName
          - name: NodeUnschedulable
      score:
        enabled:
          - name: NodeResourcesBalancedAllocation
            weight: 1
          - name: ImageLocality
            weight: 1
          - name: NodeResourcesFit
            weight: 1
          - name: NodeAffinity
            weight: 1
    extenders:
      - urlPrefix: "http://localhost:8000/api/v1"
        filterVerb: "filter"
        prioritizeVerb: "priority"
        bindVerb: "bind"
        weight: 5
        enableHTTPS: false
        nodeCacheCapable: false
        managedResources:
          - name: "edge.computing/power"
            ignoredByScheduler: true
        ignorable: true 